# Generated by Django 3.2.3 on 2024-01-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240127_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'ordering': ('-id',), 'verbose_name': 'Favorite Recipe', 'verbose_name_plural': 'Favorite Recipes'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('-id',), 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-id',), 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'ordering': ('-id',), 'verbose_name': 'Shopping List', 'verbose_name_plural': 'Shopping Lists'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-id',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
