# Generated by Django 3.2.3 on 2024-01-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240119_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
