# Generated by Django 3.2.3 on 2024-02-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240205_1028'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_name_owner',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('subscriber', 'subscribed_to'), name='unique_subscriber_subscribed_to'),
        ),
    ]
