# Generated by Django 3.2.3 on 2024-02-06 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_foodgramuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username.', regex='^[\\w.@+-]+$')], verbose_name='Username'),
        ),
    ]
